CREATE TABLE HPTRECEPTION(
	RESNO 		NUMBER(20) 		CONSTRAINT HPTRECEPTION_RESNO_PK PRIMARY KEY
,	REPEMAIL 	VARCHAR2(50) 	CONSTRAINT HPTRECEPTION_REPEMAIL_NN NOT NULL
,	PNAME 	    VARCHAR2(20) 	CONSTRAINT HPTRECEPTION_PNAME_NN NOT NULL
,	TXLIST 		VARCHAR2(20) 	CONSTRAINT HPTRECEPTION_TXLIST_NN NOT NULL
,	RDATE		DATE 			DEFAULT    SYSDATE
,   STATUS      VARCHAR2(20)    DEFAULT    '접수 대기'
,   RTCOUNT     NUMBER(5)       DEFAULT    0
, 	CONSTRAINT 	HPTRECEPTION_RESNO_FK FOREIGN KEY (RESNO) REFERENCES USERRESERVATION (RESNO) ON DELETE CASCADE
,   CONSTRAINT  HPTRECEPTION_REPEMAIL_FK FOREIGN KEY (REPEMAIL) REFERENCES HOSPITAL (REPEMAIL)
);

CREATE SEQUENCE HPTRECEPTION_RESNO_SEQ
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999
	NOCYCLE;

INSERT INTO HPTRECEPTION (RESNO, REPEMAIL, PNAME, TXLIST, STATUS, RDATE)
VALUES	(HPTRECEPTION_RESNO_SEQ.NEXTVAL, 'LONGLEE@DAUM.NET', '이성구', '영유아검진', '진료완료',
CASE
    WHEN STATUS = '접수대기' THEN NULL
    ELSE SYSDATE
END);

INSERT INTO HPTRECEPTION (RESNO, REPEMAIL, PNAME, TXLIST, STATUS, RDATE)
VALUES	(MEMBER_ID_SEQ.NEXTVAL, 'ANN@NAVER.COM', '안유진', '소아진료', '접수대기'
CASE
    WHEN STATUS = '접수대기' THEN NULL
    ELSE SYSDATE
END);
);

COMMIT;

SELECT * FROM HPTRECEPTION;